FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
# 同理，npm 源也允许构建参数覆盖
ARG NPM_REGISTRY=https://registry.npmmirror.com
RUN npm install --registry=${NPM_REGISTRY}

COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
